package PojosClases;
// Generated 03-mar-2018 13:28:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Atracciones generated by hbm2java
 */
public class Atracciones  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private int edad;
     private Date enMarcha;
     private int idParqueA;

    public Atracciones() {
    }

    public Atracciones(String nombre, int edad,int idParqueA) {
       this.nombre = nombre;
       this.edad = edad;
       this.idParqueA = idParqueA;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
 

    public int getIdParqueA() {
        return this.idParqueA;
    }
    
    public void setIdParqueA(int idParqueA) {
        this.idParqueA = idParqueA;
    }




}


