package PojosClases;
// Generated 03-mar-2018 13:28:00 by Hibernate Tools 4.3.1



/**
 * Cadena generated by hbm2java
 */
public class Cadena  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private int capital;

    public Cadena() {
    }

    public Cadena(String nombre, int capital) {
       this.nombre = nombre;
       this.capital = capital;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCapital() {
        return this.capital;
    }
    
    public void setCapital(int capital) {
        this.capital = capital;
    }




}


