package PojosClases;
// Generated 03-mar-2018 13:28:00 by Hibernate Tools 4.3.1



/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellidos;
     private String puesto;
     private int idAtraccion;
     private int sueldo;

    public Empleado() {
    }

    public Empleado(String nombre, String apellidos, String puesto, int idAtraccion, int sueldo) {
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.puesto = puesto;
       this.idAtraccion = idAtraccion;
       this.sueldo = sueldo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public int getIdAtraccion() {
        return this.idAtraccion;
    }
    
    public void setIdAtraccion(int idAtraccion) {
        this.idAtraccion = idAtraccion;
    }
    public int getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(int sueldo) {
        this.sueldo = sueldo;
    }

    @Override
    public String toString() {
        return "Empleado{" + "id=" + id + ", nombre=" + nombre + ", apellidos=" + apellidos + ", puesto=" + puesto + ", idAtraccion=" + idAtraccion + ", sueldo=" + sueldo + '}';
    }




}


