package PojosClases;
// Generated 03-mar-2018 13:28:00 by Hibernate Tools 4.3.1



/**
 * ParqueAtracciones generated by hbm2java
 */
public class ParqueAtracciones  implements java.io.Serializable {


     private Integer idParque;
     private String nombreParque;
     private String ciudadParque;
     private int presupuesto;
     private int idCadena;

    public ParqueAtracciones() {
        this.nombreParque=null;
        this.ciudadParque = null;
       this.presupuesto = 0;
       this.idCadena = 0;
    }

    public ParqueAtracciones(String nombreParque, String ciudadParque, int presupuesto, int idCadena) {
       this.nombreParque = nombreParque;
       this.ciudadParque = ciudadParque;
       this.presupuesto = presupuesto;
       this.idCadena = idCadena;
    }
   
    public Integer getIdParque() {
        return this.idParque;
    }
    
    public void setIdParque(Integer idParque) {
        this.idParque = idParque;
    }
    public String getNombreParque() {
        return this.nombreParque;
    }
    
    public void setNombreParque(String nombreParque) {
        this.nombreParque = nombreParque;
    }
    public String getCiudadParque() {
        return this.ciudadParque;
    }
    
    public void setCiudadParque(String ciudadParque) {
        this.ciudadParque = ciudadParque;
    }
    public int getPresupuesto() {
        return this.presupuesto;
    }
    
    public void setPresupuesto(int presupuesto) {
        this.presupuesto = presupuesto;
    }
    public int getIdCadena() {
        return this.idCadena;
    }
    
    public void setIdCadena(int idCadena) {
        this.idCadena = idCadena;
    }




}


